export const hsk1Words = [
  { Chinese: "爱", Pinyin: "ài", Russian: "любовь" },
  { Chinese: "八", Pinyin: "bā", Russian: "восемь" },
  { Chinese: "爸爸", Pinyin: "bàba", Russian: "папа" },
  { Chinese: "杯子", Pinyin: "bēizi", Russian: "стакан" },
  { Chinese: "北京", Pinyin: "běijīng", Russian: "Пекин" },
  { Chinese: "本", Pinyin: "běn", Russian: "книга" },
  { Chinese: "不客气", Pinyin: "búkèqì", Russian: "пожалуйста" },
  { Chinese: "不", Pinyin: "bù", Russian: "не" },
  { Chinese: "菜", Pinyin: "cài", Russian: "блюдо" },
  { Chinese: "茶", Pinyin: "chá", Russian: "чай" },
  { Chinese: "吃", Pinyin: "chī", Russian: "есть" },
  { Chinese: "出租车", Pinyin: "chūzūchē", Russian: "такси" },
  { Chinese: "打电话", Pinyin: "dǎdiànhuà", Russian: "звонить по телефону" },
  { Chinese: "大", Pinyin: "dà", Russian: "большой" },
  { Chinese: "的", Pinyin: "de", Russian: "из" },
  { Chinese: "点", Pinyin: "diǎn", Russian: "точка" },
  { Chinese: "电脑", Pinyin: "diànnǎo", Russian: "компьютер" },
  { Chinese: "电视", Pinyin: "diànshì", Russian: "телевизор" },
  { Chinese: "电影", Pinyin: "diànyǐng", Russian: "фильм" },
  { Chinese: "东西", Pinyin: "dōngxi", Russian: "вещь" },
  { Chinese: "都", Pinyin: "dōu", Russian: "все" },
  { Chinese: "读", Pinyin: "dú", Russian: "читать" },
  { Chinese: "对不起", Pinyin: "duìbuqǐ", Russian: "извините" },
  { Chinese: "多", Pinyin: "duō", Russian: "много" },
  { Chinese: "多少", Pinyin: "duōshǎo", Russian: "сколько" },
  { Chinese: "儿子", Pinyin: "érzi", Russian: "сын" },
  { Chinese: "二", Pinyin: "èr", Russian: "два" },
  { Chinese: "饭店", Pinyin: "fàndiàn", Russian: "ресторан" },
  { Chinese: "飞机", Pinyin: "fēijī", Russian: "самолет" },
  { Chinese: "分钟", Pinyin: "fēnzhōng", Russian: "минута" },
  { Chinese: "高兴", Pinyin: "gāoxìng", Russian: "счастливый" },
  { Chinese: "个", Pinyin: "gè", Russian: "индивидуальный" },
  { Chinese: "工作", Pinyin: "gōngzuò", Russian: "работа" },
  { Chinese: "狗", Pinyin: "gǒu", Russian: "собака" },
  { Chinese: "汉语", Pinyin: "hànyǔ", Russian: "китайский язык" },
  { Chinese: "好", Pinyin: "hǎo", Russian: "хороший" },
  { Chinese: "号", Pinyin: "hào", Russian: "номер" },
  { Chinese: "喝", Pinyin: "hē", Russian: "пить" },
  { Chinese: "和", Pinyin: "hé", Russian: "и" },
  { Chinese: "很", Pinyin: "hěn", Russian: "очень" },
  { Chinese: "后面", Pinyin: "hòumiàn", Russian: "задний" },
  { Chinese: "回", Pinyin: "huí", Russian: "вернуться" },
  { Chinese: "会", Pinyin: "huì", Russian: "собрание" },
  { Chinese: "几", Pinyin: "jǐ", Russian: "сколько" },
  { Chinese: "家", Pinyin: "jiā", Russian: "дом" },
  { Chinese: "叫", Pinyin: "jiào", Russian: "звать" },
  { Chinese: "今天", Pinyin: "jīntiān", Russian: "сегодня" },
  { Chinese: "九", Pinyin: "jiǔ", Russian: "девять" },
  { Chinese: "开", Pinyin: "kāi", Russian: "открыть" },
  { Chinese: "看", Pinyin: "kàn", Russian: "смотреть" },
  { Chinese: "看见", Pinyin: "kànjiàn", Russian: "увидеть" },
  { Chinese: "块", Pinyin: "kuài", Russian: "кусок" },
  { Chinese: "来", Pinyin: "lái", Russian: "приходить" },
  { Chinese: "老师", Pinyin: "lǎoshī", Russian: "учитель" },
  { Chinese: "了", Pinyin: "le", Russian: "закончилось" },
  { Chinese: "冷", Pinyin: "lěng", Russian: "холодный" },
  { Chinese: "里", Pinyin: "lǐ", Russian: "внутри" },
  { Chinese: "六", Pinyin: "liù", Russian: "шесть" },
  { Chinese: "吗", Pinyin: "ma", Russian: "вопросительная частица" },
  { Chinese: "妈妈", Pinyin: "māma", Russian: "мама" },
  { Chinese: "买", Pinyin: "mǎi", Russian: "купить" },
  { Chinese: "猫", Pinyin: "māo", Russian: "кошка" },
  { Chinese: "没关系", Pinyin: "méi guānxi", Russian: "ничего страшного" },
  { Chinese: "没有", Pinyin: "méiyǒu", Russian: "нет" },
  { Chinese: "米饭", Pinyin: "mǐfàn", Russian: "рис" },
  { Chinese: "名字", Pinyin: "míngzi", Russian: "имя" },
  { Chinese: "明天", Pinyin: "míngtiān", Russian: "завтра" },
  { Chinese: "哪", Pinyin: "nǎ", Russian: "какой" },
  { Chinese: "哪儿", Pinyin: "nǎ er", Russian: "где" },
  { Chinese: "那", Pinyin: "nà", Russian: "тот" },
  { Chinese: "呢", Pinyin: "ne", Russian: "частица вопроса" },
  { Chinese: "能", Pinyin: "néng", Russian: "мочь" },
  { Chinese: "你", Pinyin: "nǐ", Russian: "ты" },
  { Chinese: "年", Pinyin: "nián", Russian: "год" },
  { Chinese: "女儿", Pinyin: "nǚ ér", Russian: "дочь" },
  { Chinese: "朋友", Pinyin: "péngyǒu", Russian: "друг" },
  { Chinese: "漂亮", Pinyin: "piàoliang", Russian: "красивый" },
  { Chinese: "苹果", Pinyin: "píngguǒ", Russian: "яблоко" },
  { Chinese: "七", Pinyin: "qī", Russian: "семь" },
  { Chinese: "前面", Pinyin: "qiánmiàn", Russian: "перед" },
  { Chinese: "钱", Pinyin: "qián", Russian: "деньги" },
  { Chinese: "请", Pinyin: "qǐng", Russian: "пожалуйста" },
  { Chinese: "去", Pinyin: "qù", Russian: "идти" },
  { Chinese: "热", Pinyin: "rè", Russian: "горячий" },
  { Chinese: "人", Pinyin: "rén", Russian: "человек" },
  { Chinese: "认识", Pinyin: "rènshi", Russian: "знать" },
  { Chinese: "三", Pinyin: "sān", Russian: "три" },
  { Chinese: "商店", Pinyin: "shāngdiàn", Russian: "магазин" },
  { Chinese: "上", Pinyin: "shàng", Russian: "вверх" },
  { Chinese: "上午", Pinyin: "shàngwǔ", Russian: "утро" },
  { Chinese: "少", Pinyin: "shǎo", Russian: "мало" },
  { Chinese: "谁", Pinyin: "shéi", Russian: "кто" },
  { Chinese: "什么", Pinyin: "shénme", Russian: "что" },
  { Chinese: "十", Pinyin: "shí", Russian: "десять" },
  { Chinese: "时候", Pinyin: "shíhòu", Russian: "время" },
  { Chinese: "是", Pinyin: "shì", Russian: "быть" },
  { Chinese: "书", Pinyin: "shū", Russian: "книга" },
  { Chinese: "水", Pinyin: "shuǐ", Russian: "вода" },
  { Chinese: "水果", Pinyin: "shuǐguǒ", Russian: "фрукт" },
  { Chinese: "睡觉", Pinyin: "shuìjiào", Russian: "спать" },
  { Chinese: "说", Pinyin: "shuō", Russian: "говорить" },
  { Chinese: "四", Pinyin: "sì", Russian: "четыре" },
  { Chinese: "岁", Pinyin: "suì", Russian: "год (возраст)" },
  { Chinese: "他", Pinyin: "tā", Russian: "он" },
  { Chinese: "她", Pinyin: "tā", Russian: "она" },
  { Chinese: "太", Pinyin: "tài", Russian: "слишком" },
  { Chinese: "天气", Pinyin: "tiānqì", Russian: "погода" },
  { Chinese: "听", Pinyin: "tīng", Russian: "слушать" },
  { Chinese: "同学", Pinyin: "tóngxué", Russian: "одноклассник" },
  { Chinese: "喂", Pinyin: "wèi", Russian: "алло" },
  { Chinese: "我", Pinyin: "wǒ", Russian: "я" },
  { Chinese: "我们", Pinyin: "wǒmen", Russian: "мы" },
  { Chinese: "五", Pinyin: "wǔ", Russian: "пять" },
  { Chinese: "喜欢", Pinyin: "xǐhuan", Russian: "нравиться" },
  { Chinese: "下", Pinyin: "xià", Russian: "ниже" },
  { Chinese: "下午", Pinyin: "xiàwǔ", Russian: "после полудня" },
  { Chinese: "下雨", Pinyin: "xiàyǔ", Russian: "идет дождь" },
  { Chinese: "先生", Pinyin: "xiānsheng", Russian: "господин" },
  { Chinese: "现在", Pinyin: "xiànzài", Russian: "сейчас" },
  { Chinese: "想", Pinyin: "xiǎng", Russian: "думать" },
  { Chinese: "小", Pinyin: "xiǎo", Russian: "маленький" },
  { Chinese: "小姐", Pinyin: "xiǎojie", Russian: "мисс" },
  { Chinese: "些", Pinyin: "xiē", Russian: "несколько" },
  { Chinese: "写", Pinyin: "xiě", Russian: "писать" },
  { Chinese: "谢谢", Pinyin: "xièxie", Russian: "спасибо" },
  { Chinese: "星期", Pinyin: "xīngqī", Russian: "неделя" },
  { Chinese: "学生", Pinyin: "xuésheng", Russian: "студент" },
  { Chinese: "学习", Pinyin: "xuéxí", Russian: "учиться" },
  { Chinese: "学校", Pinyin: "xuéxiào", Russian: "школа" },
  { Chinese: "一", Pinyin: "yī", Russian: "один" },
  { Chinese: "一点儿", Pinyin: "yīdiǎnr", Russian: "немного" },
  { Chinese: "医生", Pinyin: "yīshēng", Russian: "врач" },
  { Chinese: "医院", Pinyin: "yīyuàn", Russian: "больница" },
  { Chinese: "衣服", Pinyin: "yīfu", Russian: "одежда" },
  { Chinese: "椅子", Pinyin: "yǐzi", Russian: "стул" },
  { Chinese: "有", Pinyin: "yǒu", Russian: "иметь" },
  { Chinese: "月", Pinyin: "yuè", Russian: "месяц" },
  { Chinese: "再见", Pinyin: "zàijiàn", Russian: "до свидания" },
  { Chinese: "在", Pinyin: "zài", Russian: "находиться" },
  { Chinese: "怎么", Pinyin: "zěnme", Russian: "как?" },
  { Chinese: "怎么样", Pinyin: "zěnme yàng", Russian: "как дела?" },
  { Chinese: "这", Pinyin: "zhè", Russian: "это" },
  { Chinese: "中国", Pinyin: "zhōngguó", Russian: "Китай" },
  { Chinese: "中午", Pinyin: "zhōngwǔ", Russian: "полдень" },
  { Chinese: "住", Pinyin: "zhù", Russian: "жить" },
  { Chinese: "桌子", Pinyin: "zhuōzi", Russian: "стол" },
  { Chinese: "字", Pinyin: "zì", Russian: "буква" },
  { Chinese: "昨天", Pinyin: "zuótiān", Russian: "вчера" },
  { Chinese: "做", Pinyin: "zuò", Russian: "делать" },
  { Chinese: "坐", Pinyin: "zuò", Russian: "сидеть" },
];

export type hsk1WordsType = typeof hsk1Words;
export type hsk1WordType = typeof hsk1Words[number];